---
- name: Ensure openssl is installed
  become: true
  ansible.builtin.package:
    name: openssl
    state: present

- name: Ensure remote folder is present
  become: true
  ansible.builtin.file:
    path: '{{ dhparams_remote_directory }}'
    state: directory
    mode: '{{ dhparams_directory_mode }}'

- name: Get current key-size
  ansible.builtin.shell: >-
    openssl dhparam -in
    '{{ dhparams_remote_directory }}/{{ dhparams_filename }}'
    -text | grep -i 'dh parameters:' |
    sed 's/.*(\([0-9]\{1,\}\) bit).*/\1/'

  register: dhparams_remote_key_size
  changed_when: false
  ignore_errors: true

- name: debuginfo
  ansible.builtin.debug:
    msg: "Key size is {{ dhparams_remote_key_size.stdout }} bits"

- name: Create local temp directory
  become: false
  ansible.builtin.tempfile:
    state: directory
  register: dhparams_temp_dir
  when:
    - dhparams_key_size|string != dhparams_remote_key_size.stdout
  delegate_to: localhost

- name: debuginfo
  ansible.builtin.debug:
    msg: "Generating a {{ dhparams_key_size }} bit key"
  when:
    - dhparams_key_size|string != dhparams_remote_key_size.stdout

- name: Generate dhparams locally. This can take a long time.
  become: false
  community.crypto.openssl_dhparam:
    path: '{{ dhparams_temp_dir.path }}/dhparams.pem'
    size: '{{ dhparams_key_size }}'
  when:
    - dhparams_key_size|string != dhparams_remote_key_size.stdout
  delegate_to: localhost

- name: Transfer dhparams to remote server
  ansible.builtin.copy:
    src: '{{ dhparams_temp_dir.path }}/dhparams.pem'
    dest: '{{ dhparams_remote_directory }}/{{ dhparams_filename }}'
    owner: '{{ dhparams_owner }}'
    group: '{{ dhparams_group }}'
    mode: '{{ dhparams_mode }}'
  when:
    - dhparams_key_size|string != dhparams_remote_key_size.stdout

- name: Remove local temp dir
  become: false
  ansible.builtin.file:
    path: '{{ dhparams_temp_dir.path }}'
    state: absent
  when: dhparams_temp_dir.path is defined

  delegate_to: localhost
