---

- name: Ensure opelssl is installed
  become: true
  package:
    name: openssl
    state: present

- name: Ensure remote folder is present
  become: true
  file:
    path: '{{ dhparams_remote_path }}'
    state: directory
    mode: '{{ dhparams_directory_mode }}'

- name: Get current key-size
  shell: "openssl dhparam -in {{ dhparams_remote_path }}/{{ dhparam_filename }} -text | grep 'DH Parameters:' | sed 's/[^0-9]*//g'"
  register: dhparam_remote_key_size
  changed_when: false

- name: Create local temp directory
  tempfile:
    state: directory
  register: temp_dir
  when:
    - dhparam_key_size != dhparams_remote_key_size.stdout
  delegate_to: localhost

- name: Generate dhparams locally. This can take a long time.
  openssl_dhparam:
    path: '{{ temp_dir.path }}/dhparams.pem'
  when:
    - dhparam_key_size != dhparams_remote_key_size.stdout
  delegate_to: localhost

- name: Transfer dhparams to remote server
  copy:
    src: '{{ temp_dir.path }}/dhparams.pem'
    dest: '{{ dhparams_remote_path }}/{{ dhparam_filename }}'
    owner: '{{ dhparams_owner }}'
    group: '{{ dhparams_group }}'
    mode: '{{ dhparams_mode }}'
  
