---
- name: Ensure openssl is installed
  become: true
  package:
    name: openssl
    state: present

- name: Ensure remote folder is present
  become: true
  file:
    path: '{{ dhparams_remote_directory }}'
    state: directory
    mode: '{{ dhparams_directory_mode }}'

- name: Get current key-size
  shell: >-
    openssl dhparam -in
    '{{ dhparams_remote_directory }}/{{ dhparams_filename }}'
    -text | grep 'DH Parameters:' | sed 's/[^0-9]*//g'
  register: dhparams_remote_key_size
  changed_when: false

- debug:
    msg: "Key size is {{ dhparams_remote_key_size.stdout }} bits"

- name: Create local temp directory
  tempfile:
    state: directory
  register: temp_dir
  when:
    - dhparams_key_size|string != dhparams_remote_key_size.stdout
  delegate_to: localhost

- name: Generate dhparams locally. This can take a long time.
  openssl_dhparam:
    path: '{{ temp_dir.path }}/dhparams.pem'
    size: '{{ dhparams_key_size }}'
  when:
    - dhparams_key_size|string != dhparams_remote_key_size.stdout
  delegate_to: localhost

- name: Transfer dhparams to remote server
  copy:
    src: '{{ temp_dir.path }}/dhparams.pem'
    dest: '{{ dhparams_remote_directory }}/{{ dhparams_filename }}'
    owner: '{{ dhparams_owner }}'
    group: '{{ dhparams_group }}'
    mode: '{{ dhparams_mode }}'
  when:
    - dhparams_key_size|string != dhparams_remote_key_size.stdout

- name: Remove local temp dir
  file:
    path: '{{ temp_dir.path }}'
    state: absent
  delegate_to: localhost
  when: temp_dir.path is defined
